version: "3.4"

services:
  client:
    restart: always
    image: client
    build: ./services/client
    ports:
      - 8080:8080

  data:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "9000:9000"

volumes:
  db-data:
