version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db

  client:
    restart: always
    image: client
    build: ./services/client
    depends_on:
      - mongo
    ports:
      - 8080:8080

volumes:
  mongodata:
